
package guifilesplitter;



    public class Alert extends javax.swing.JDialog {

    private String message;
    /** Creates new form Alert */
    public Alert(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setLocation(400,460);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jButton1 = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();

        setTitle("Oops");
        setName("Alert");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });

        getContentPane().add(jButton1, java.awt.BorderLayout.CENTER);

        jTextArea1.setColumns(25);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(1);
        jTextArea1.setPreferredSize(new java.awt.Dimension(275, 16));
        getContentPane().add(jTextArea1, java.awt.BorderLayout.NORTH);

        pack();
    }//GEN-END:initComponents

    /**Handle the OK button
     */
    private void buttonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPressed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonPressed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**Allows to set the the message of the allert box
     * @param message The string message
     */
    public void setMessage(String message)
    {
        this.message = message;
        jTextArea1.setText(message);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}



